{{- $root := . -}}
{{- range .Values.classes }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ . }}
  {{- if eq $root.Values.defaultClass . }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ . }}
  fsType: {{ $root.Values.fstype }}
{{- end }}
