{{- $root := . -}}
{{- range .Values.classes }}
{{- $currentClass := . -}}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ . }}
  {{- if eq $root.Values.defaultClass . }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ $currentClass }}
  fsType: {{ $root.Values.defaultFSType }}
{{ range $root.Values.fsTypes }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $currentClass }}-{{ . }}
  {{- if eq $root.Values.defaultClass $currentClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ $currentClass }}
  fsType: {{ . }}
---
{{ end }}
{{ end }}
