{{- $root := . -}}
{{- range .Values.classes }}
{{- $currentClass := . -}}
---
{{- if not (lookup "storage.k8s.io/v1" "StorageClass" "" $currentClass) }}
kind: StorageClass
apiVersion: "storage.k8s.io/v1"
metadata:
  name: {{ . }}
  annotations:
    helm.sh/resource-policy: "keep"
  {{- if eq $root.Values.defaultClass . }}
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: "ebs.csi.aws.com"
parameters:
  type: {{ $currentClass }}
  csi.storage.k8s.io/fstype: {{ $root.Values.defaultFSType }}
  encrypted: {{ $root.Values.encryptionEnabled | quote }}
{{- end }}
{{- range $root.Values.fsTypes }}
{{- $currentfsType := . -}}
{{- if not (lookup "storage.k8s.io/v1" "StorageClass" "" (printf "%s-%s" $currentClass $currentfsType)) }}
---
kind: StorageClass
apiVersion: "storage.k8s.io/v1"
metadata:
  name: {{ $currentClass }}-{{ . }}
  annotations:
    helm.sh/resource-policy: "keep"
provisioner: "ebs.csi.aws.com"
parameters:
  type: {{ $currentClass }}
  csi.storage.k8s.io/fstype: {{ . }}
  encrypted: {{ $root.Values.encryptionEnabled | quote }}
---
{{ end }}
{{ end }}
{{ end }}
